### ISSUE TITLE
kernel_require.rb:55:in `require': cannot load such file

### ISSUE THREAD

**Issue by tristan-k** [agilecreativity/folders_renamer#1]
I installed your gem successfully but running results in the following

```
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_support (LoadError)
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /var/lib/gems/2.1.0/gems/agile_utils-0.2.3/lib/agile_utils.rb:8:in `<top (required)>'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /var/lib/gems/2.1.0/gems/folders_renamer-0.2.3/lib/folders_renamer.rb:2:in `<top (required)>'
from /var/lib/gems/2.1.0/gems/folders_renamer-0.2.3/bin/folders_renamer:2:in `require_relative'
from /var/lib/gems/2.1.0/gems/folders_renamer-0.2.3/bin/folders_renamer:2:in `<top (required)>'
from /usr/local/bin/folders_renamer:23:in `load'
from /usr/local/bin/folders_renamer:23:in `<main>'

$ ruby --version
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
$ sudo gem list
*** LOCAL GEMS ***
activesupport-core-ext (4.0.0.3)
agile_utils (0.2.3)
bigdecimal (1.2.4)
bundler (1.10.5)
code_lister (0.2.4)
curses (1.0.1)
filename_cleaner (0.4.6)
folders_renamer (0.2.3)
io-console (0.4.2)
json (1.8.1)
minitar (0.5.4)
minitest (4.7.5)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
stringex (2.5.2)
test-unit (2.1.2.0)
thor (0.19.1)
```

**Comment by agilecreativity** [comment]
This should have been fixed in the last update. It is due to the deprecated gem which I have replaced with alternative one. Thanks for reporting the errors. If you still get any other errors please reopen the issue.
